### ISSUE TITLE
[Question] How safe really is prometheus?

### ISSUE THREAD

**Issue by ImInTheICU** [prometheus-lua/Prometheus#122]
Quick question, how safe is prometheus?
I have always wondered is it even worth using or should I go use something like moonsec-v3 OR some other available free obfuscators.

**Comment by levno-710** [comment]
As Prometheus doesn't use a lbi and modified standard lua bytecode, it is much harder to write a deobfuscator than for obfuscators like moonsec.
To this point Prometheus has not been deobfuscated.

In the end, this comes to preference.

PS: Github Issues should be used for bugs and improvements only. For questions i suggest heading to [Discussions](https://github.com/prometheus-lua/Prometheus/discussions).
