### ISSUE TITLE
Dumped!

### ISSUE THREAD

**Issue by ImInTheICU** [prometheus-lua/Prometheus#136]
https://github.com/chicagogrimreaper/prometheus-dumper/tree/main
There's now a dumper for prometheus!

**Comment by levno-710** [comment]
Did you test, if this works with constant encryption enabled?

**Comment by levno-710** [comment]
I will close this issue, as dumping doesn't work, if you're using constant encryption.
Feel free, to reopen this issue, when a dumper is released, that works with constant encryption enabled.
