### ISSUE TITLE
[BUG] obfuscation output error

### ISSUE THREAD

**Issue by 023948799e213e21b53eb83785356208** [prometheus-lua/Prometheus#138]
**Describe the bug**
When i obfuscated it on luajit and lua it outputs a loadstringed bytecode or whatevers in the top of the obfuscated which will trigger the anti tamper

**Expected behavior**
It should produce a base64 like output for the bytecode
**To Reproduce**
 
I haven't edited anything

**Screenshots**

Here's the problem
I do not know what problem it is since i only learned luau and not lua 5.1
![Screenshot_20230628-145556_Chrome](https://github.com/prometheus-lua/Prometheus/assets/100945753/937a4210-f8b7-42f3-aa21-635fab1d00c2)

**Additional context**

**Comment by levno-710** [comment]
If you are trying to obfuscate a script for luau, try adding the --LuaU command line argument, as otherwise anti tamper might be triggered on LuaU

**Comment by 023948799e213e21b53eb83785356208** [comment]
> If you are trying to obfuscate a script for luau, try adding the --LuaU command line argument, as otherwise anti tamper might be triggered on LuaU. Lmk if this helps

Nope, Doesn't seem to help at all. I tried older versions and they work just fine probably from the main prometheus src.

**Comment by 023948799e213e21b53eb83785356208** [comment]
It was a new update and it works fine
