### ISSUE TITLE
Roblox terms of service update

### ISSUE THREAD

**Issue by nekohacker591** [prometheus-lua/Prometheus#177]
not really a bug but more or so changes needed

roblox bans the sue of require remote asset id, getfenv and setfenv , loadstring thats thats likely all u need to worry about

**Comment by Infraction7** [comment]
no u don't
Roblox bans these only in distributed models aka toolbox

**Comment by SpinnySpiwal** [comment]
no, just _G["g".."et"..table.concat({"f","e"}).."nv"]
