### ISSUE TITLE
Youtube Video Tutorial?

### ISSUE THREAD

**Issue by Kiraaa02** [prometheus-lua/Prometheus#40]
I'm new to this kind of stuff, and would like to obfuscate my script, I hardly understand it. Will there be a youtube tutorial?

Thanks.

**Comment by levno-710** [comment]
Probably not within the next few months, but once the first non-Alpha release is done, i might create a video tutorial.

**Comment by Brohammer5** [comment]
Hi, 
It was for me to, but you just download the windows release or (other releases) and type in command line: `prometheus.exe --preset Medium yourfile.lua`

**Comment by 023948799e213e21b53eb83785356208** [comment]
so this is the tutorial
lua ./prometheus.exe --preset Strong ./name of the file.lua
You will get an filename_obfuscated.lua
Make sure you have lua 5.1.5

**Comment by levno-710** [comment]
https://www.youtube.com/watch?v=_Vyor64gTvU
