### ISSUE TITLE
[Feature Request] In-Browser Obfuscator

### ISSUE THREAD

**Issue by CoolOppo** [prometheus-lua/Prometheus#61]
I would like to have the same type of thing javascript-obfuscator has where you can just paste the code in your browser and it pops out.

Just got the latest version of Lua to compile with emscripten...hopefully I can make a simple page to run Prometheus on.

**Comment by CoolOppo** [comment]
Ran out of patience lol. But if you want how I compiled it, just changed the Makefile to remove references to the specific programs so that when using `emmake` it would override them.

**Comment by Brohammer5** [comment]
Cool Idea but Why would you have a Makefile, this obsfucator is full lua which wouldn't require C

**Comment by pnlmon** [comment]
I've created a website for this: https://prometheus-web-hosting.web.app

**Comment by levno-710** [comment]
Very nice.
