### ISSUE TITLE
[BUG] Luau - Ternary operators not supported

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [prometheus-lua/Prometheus#82]
**Describe the bug**
It looks like ternary operators (``x = if condition then true else false``) aren't supported:
```
PROMETHEUS: Applying Obfuscation Pipeline to .\test.luau ...
PROMETHEUS: Parsing ...
PROMETHEUS: Parsing Error at Position 1:10, Unexpected Token "if". Expected a Expression!
```

**Expected behavior**
Ternary operators for luau to be supported and not error.

**To Reproduce**
1. Use the following test file
```
local x = if true then "yes" else "no"
```
2. Input the file to Prometheus either via a lua script or cli

If your problem is a non-working obfuscated file, please also include a minimal source code example, your config file as well as the output file that you got.

**Screenshots**

**Additional context**
Windows 11 x64, Lua 5,1

**Comment by levno-710** [comment]
I didn't even know these were a thing in LuaU

**Comment by RealEthanPlayzDev** [comment]
> I didn't even know these were a thing in LuaU

Well it's relatively new you can say, you can check https://luau-lang.org/syntax#if-then-else-expressions

**Comment by LolloDev5123** [comment]
Some ternary operators don't use if and then
Example:
```lua
local e = a and h or l -- If a is true, e is h, if a is false, e is l
```

**Comment by RealEthanPlayzDev** [comment]
> Some ternary operators don't use if and then
Those ternary operators are already native lua, and is semi-ternary operator (it isn't technically), since if ``a`` was true but ``h`` was false it'll go to l anyways.

This report is about Luau actual ternary operators not being supported

**Comment by levno-710** [comment]
related to #114
